# application-aws.yaml
# AWS 환경 설정 (환경변수를 통해 설정값 주입)

# AWS 환경용 데이터 로드 설정
spring:
  sql:
    init:
      data-locations: classpath:data.sql

# 헬스체크 엔드포인트 설정
management:
  endpoints:
    web:
      exposure:
        include: health, info   # 헬스체크와 정보 엔드포인트 노출
  endpoint:
    health:
      show-details: always      # 헬스체크 상세 정보 표시
  health:
    db:
      enabled: true # 데이터베이스 헬스체크 활성화

file:
  upload-dir: s3
  base-url: https://${aws.s3.bucket}.s3.${aws.region}.amazonaws.com/ 